/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disruptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Disruptions */
        get: operations["list_disruptions_api_v1_disruptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disruptions/{disruption_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Disruption */
        get: operations["get_disruption_api_v1_disruptions__disruption_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disruptions/{disruption_id}/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Disruption Impact
         * @description Compute and return which shipments are impacted by this disruption,
         *     ranked by impact score descending. Each result carries a Decision.
         */
        get: operations["get_disruption_impact_api_v1_disruptions__disruption_id__impact_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shipments */
        get: operations["list_shipments_api_v1_shipments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{shipment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shipment */
        get: operations["get_shipment_api_v1_shipments__shipment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{shipment_id}/readings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shipment Readings
         * @description Returns sensor readings and data gaps for a shipment in chronological order.
         *     Gaps are interleaved with readings at their correct position.
         *     Response: { readings: [...], gaps: [...] }
         */
        get: operations["get_shipment_readings_api_v1_shipments__shipment_id__readings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{shipment_id}/excursions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shipment Excursions */
        get: operations["get_shipment_excursions_api_v1_shipments__shipment_id__excursions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{shipment_id}/reroutes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shipment Reroutes */
        get: operations["get_shipment_reroutes_api_v1_shipments__shipment_id__reroutes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shipments/{shipment_id}/reroutes/{reroute_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Reroute
         * @description Mark a reroute option as accepted (stub — persists a flag).
         */
        post: operations["accept_reroute_api_v1_shipments__shipment_id__reroutes__reroute_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cold-chain/excursions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Excursions
         * @description Return open and recent excursions, ranked by severity then actionability.
         *     Severity order: critical > major > minor > informational.
         *     Actionability: detectedBeforeDelivery=True ranks above post-mortem.
         */
        get: operations["list_excursions_api_v1_cold_chain_excursions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cold-chain/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Readings
         * @description Accept a batch of sensor readings. Deduplicates by canonical reading ID.
         *     Returns count of new readings inserted.
         */
        post: operations["ingest_readings_api_v1_cold_chain_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleet/idle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Idle Assets
         * @description Return idle assets ranked by wasted capacity-hours (capacity × idle_hours).
         *     Includes capacity_hours field alongside each asset for transparency.
         */
        get: operations["list_idle_assets_api_v1_fleet_idle_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fleet/redeployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Redeployment Matches
         * @description Return pre-computed redeployment matches from the DB (seeded from fixture).
         *     Sorted by hours_to_position ascending.
         */
        get: operations["list_redeployment_matches_api_v1_fleet_redeployments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/priority-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Priority Queue
         * @description The merged, ranked operator worklist.
         *
         *     Merges open excursions, shipment exceptions/delays, and idle assets into
         *     one comparable ordering. Each item carries its score and score_components
         *     so the operator can see why it ranks where it does.
         */
        get: operations["get_priority_queue_api_v1_priority_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events Disabled */
        get: operations["stream_events_disabled_api_v1_stream_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query Assistant
         * @description Free-text operator query. Routes to engine tools and composes an answer.
         *
         *     - If the language model is available (WATSONX_ENABLED=true), it explains
         *       the engine output in natural language.
         *     - If the language model is unavailable, a deterministic template response
         *       is returned. The system is fully functional in either mode.
         *     - The assistant never answers from its own knowledge when engines return nothing.
         */
        post: operations["query_assistant_api_v1_assistant_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Cargo */
        Cargo: {
            /** Description */
            description: string;
            /** Valueusd */
            valueUsd: number;
            /** Iscoldchain */
            isColdChain: boolean;
            /** Temprangec */
            tempRangeC?: {
                [key: string]: number;
            } | null;
            regulatoryRegime?: components["schemas"]["RegulatoryRegime"] | null;
        };
        /** CircleArea */
        CircleArea: {
            center: components["schemas"]["GeoPoint"];
            /** Radiuskm */
            radiusKm: number;
        };
        /**
         * ColdChainContinuity
         * @enum {string}
         */
        ColdChainContinuity: "maintained" | "at_risk" | "broken";
        /**
         * Decision
         * @description Attached to every classification, score, and ranking returned by an engine.
         *     Every verdict-bearing response carries one of these — the system is fully
         *     auditable without a language model.
         */
        Decision: {
            /** Rule Pack Id */
            rule_pack_id: string;
            /** Rule Pack Version */
            rule_pack_version: string;
            /** Rule Id */
            rule_id: string;
            /** Citation */
            citation: string;
            /** Inputs */
            inputs: {
                [key: string]: number | string;
            };
            /** Evidence Record Ids */
            evidence_record_ids: string[];
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Engine Version */
            engine_version: string;
        };
        /** Disruption */
        Disruption: {
            /** Id */
            id: string;
            type: components["schemas"]["DisruptionType"];
            /** Headline */
            headline: string;
            /** Detail */
            detail: string;
            severity: components["schemas"]["Severity"];
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Expectedresolutionat */
            expectedResolutionAt?: string | null;
            /** Confidence */
            confidence: number;
            /** Source */
            source: string;
            /** Affectedarea */
            affectedArea: components["schemas"]["CircleArea"] | components["schemas"]["PolygonArea"];
            /** Affectednodes */
            affectedNodes: string[];
        };
        /**
         * DisruptionType
         * @enum {string}
         */
        DisruptionType: "weather" | "labour_action" | "geopolitical" | "congestion" | "infrastructure" | "customs";
        /** Excursion */
        Excursion: {
            /** Id */
            id: string;
            /** Shipmentid */
            shipmentId: string;
            /** Legid */
            legId: string;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Endedat */
            endedAt?: string | null;
            /** Peaktempc */
            peakTempC: number;
            /** Minutesoutofrange */
            minutesOutOfRange: number;
            /** Degreeminutes */
            degreeMinutes: number;
            /** Meankinetictempc */
            meanKineticTempC: number;
            severity: components["schemas"]["Severity"];
            /** Regulatorybasis */
            regulatoryBasis: string;
            disposition: components["schemas"]["ExcursionDisposition"];
            /** Evidencereadingids */
            evidenceReadingIds: string[];
            /** Detectedbeforedelivery */
            detectedBeforeDelivery: boolean;
        };
        /**
         * ExcursionDisposition
         * @enum {string}
         */
        ExcursionDisposition: "release" | "quarantine_pending_QA" | "reject";
        /** GeoPoint */
        GeoPoint: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Label */
            label: string;
            /** Unlocode */
            unlocode?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImpactScore
         * @description Score components for a disruption→shipment impact, returned separately.
         */
        ImpactScore: {
            /** Shipment Id */
            shipment_id: string;
            /** Disruption Id */
            disruption_id: string;
            /** Delay Hours */
            delay_hours: number;
            /** Cargo Value Usd */
            cargo_value_usd: number;
            /** Cold Chain Exposure */
            cold_chain_exposure: boolean;
            /** Cascade Legs */
            cascade_legs: number;
            /** Total Score */
            total_score: number;
            decision: components["schemas"]["Decision"];
        };
        /** Leg */
        Leg: {
            /** Id */
            id: string;
            /** Sequence */
            sequence: number;
            mode: components["schemas"]["Mode"];
            /** Carrier */
            carrier: string;
            from: components["schemas"]["GeoPoint"];
            to: components["schemas"]["GeoPoint"];
            /**
             * Departsat
             * Format: date-time
             */
            departsAt: string;
            /**
             * Arrivesat
             * Format: date-time
             */
            arrivesAt: string;
            status: components["schemas"]["LegStatus"];
        };
        /**
         * LegStatus
         * @enum {string}
         */
        LegStatus: "completed" | "in_transit" | "scheduled" | "blocked";
        /**
         * Mode
         * @enum {string}
         */
        Mode: "ocean" | "air" | "road" | "rail";
        /** PolygonArea */
        PolygonArea: {
            /** Polygon */
            polygon: [
                number,
                number
            ][];
        };
        /** QueryRequest */
        QueryRequest: {
            /** Query */
            query: string;
        };
        /** RedeploymentMatch */
        RedeploymentMatch: {
            /** Assetid */
            assetId: string;
            /** Shipmentid */
            shipmentId: string;
            /** Distancekm */
            distanceKm: number;
            /** Hourstoposition */
            hoursToPosition: number;
            /** Utilisationgainpct */
            utilisationGainPct: number;
            /** Rationale */
            rationale: string;
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
        };
        /**
         * RegulatoryRegime
         * @description Regulatory regime for cold-chain cargo. Field is optional; absence = no regime.
         * @enum {string}
         */
        RegulatoryRegime: "GDP" | "WHO_PQS" | "USP_1079" | "FSMA";
        /**
         * RerouteFeasibility
         * @enum {string}
         */
        RerouteFeasibility: "confirmed" | "likely" | "speculative";
        /** RerouteOption */
        RerouteOption: {
            /** Id */
            id: string;
            /** Shipmentid */
            shipmentId: string;
            /** Summary */
            summary: string;
            /** Replaceslegids */
            replacesLegIds: string[];
            /** Newlegs */
            newLegs: components["schemas"]["Leg"][];
            /** Deltadays */
            deltaDays: number;
            /** Deltacostusd */
            deltaCostUsd: number;
            /** Co2Deltakg */
            co2DeltaKg: number;
            coldChainContinuity: components["schemas"]["ColdChainContinuity"];
            /** Coldchaincontinuityreason */
            coldChainContinuityReason?: string | null;
            feasibility: components["schemas"]["RerouteFeasibility"];
            /** Constraints */
            constraints: string[];
            /** Rationale */
            rationale: string;
            /** Recommended */
            recommended: boolean;
        };
        /** SensorReading */
        SensorReading: {
            /** Shipmentid */
            shipmentId: string;
            /** Sensorid */
            sensorId: string;
            /** Legid */
            legId: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Tempc */
            tempC: number;
            /** Humiditypct */
            humidityPct?: number | null;
            /** Dooropen */
            doorOpen?: boolean | null;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "informational" | "minor" | "major" | "critical";
        /** Shipment */
        Shipment: {
            /** Id */
            id: string;
            /** Reference */
            reference: string;
            /** Shipper */
            shipper: string;
            /** Consignee */
            consignee: string;
            origin: components["schemas"]["GeoPoint"];
            destination: components["schemas"]["GeoPoint"];
            /** Legs */
            legs: components["schemas"]["Leg"][];
            cargo: components["schemas"]["Cargo"];
            /**
             * Etaoriginal
             * Format: date-time
             */
            etaOriginal: string;
            /**
             * Etaprojected
             * Format: date-time
             */
            etaProjected: string;
            status: components["schemas"]["ShipmentStatus"];
            /** Impactedby */
            impactedBy: string[];
            /** Riskscore */
            riskScore: number;
        };
        /**
         * ShipmentStatus
         * @enum {string}
         */
        ShipmentStatus: "on_track" | "at_risk" | "delayed" | "exception";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_disruptions_api_v1_disruptions_get: {
        parameters: {
            query?: {
                severity?: string | null;
                type?: string | null;
                active_only?: boolean;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Disruption"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_disruption_api_v1_disruptions__disruption_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disruption_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Disruption"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_disruption_impact_api_v1_disruptions__disruption_id__impact_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                disruption_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpactScore"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shipments_api_v1_shipments_get: {
        parameters: {
            query?: {
                status?: string | null;
                cold_chain?: boolean | null;
                value_min?: number | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shipment_api_v1_shipments__shipment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shipment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shipment_readings_api_v1_shipments__shipment_id__readings_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                shipment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shipment_excursions_api_v1_shipments__shipment_id__excursions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Excursion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shipment_reroutes_api_v1_shipments__shipment_id__reroutes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerouteOption"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_reroute_api_v1_shipments__shipment_id__reroutes__reroute_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: string;
                reroute_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_excursions_api_v1_cold_chain_excursions_get: {
        parameters: {
            query?: {
                open_only?: boolean;
                severity?: string | null;
                shipment_id?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Excursion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_readings_api_v1_cold_chain_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensorReading"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_idle_assets_api_v1_fleet_idle_get: {
        parameters: {
            query?: {
                reefer_only?: boolean;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_redeployment_matches_api_v1_fleet_redeployments_get: {
        parameters: {
            query?: {
                asset_id?: string | null;
                shipment_id?: string | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedeploymentMatch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_priority_queue_api_v1_priority_queue_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_disabled_api_v1_stream_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    query_assistant_api_v1_assistant_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
