"""initial_schema

Revision ID: e5eecc450db2
Revises: 
Create Date: 2026-09-15 00:17:54.467725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5eecc450db2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_nodes',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('network_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_nodes_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_nodes_node_type'), ['node_type'], unique=False)

    op.create_table('lanes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_node', sa.String(length=10), nullable=False),
    sa.Column('to_node', sa.String(length=10), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('carrier', sa.String(), nullable=False),
    sa.Column('transit_hours', sa.Float(), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('reefer_capable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['from_node'], ['network_nodes.code'], ),
    sa.ForeignKeyConstraint(['to_node'], ['network_nodes.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.create_index('ix_lanes_from_node_mode', ['from_node', 'mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_lanes_mode'), ['mode'], unique=False)

    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.create_index('ix_sensor_readings_shipment_ts', ['shipment_id', 'timestamp'], unique=False)
        batch_op.create_unique_constraint('uq_sensor_reading', ['sensor_id', 'timestamp'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sensor_reading', type_='unique')
        batch_op.drop_index('ix_sensor_readings_shipment_ts')

    with op.batch_alter_table('lanes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lanes_mode'))
        batch_op.drop_index('ix_lanes_from_node_mode')

    op.drop_table('lanes')
    with op.batch_alter_table('network_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_nodes_node_type'))
        batch_op.drop_index(batch_op.f('ix_network_nodes_country'))

    op.drop_table('network_nodes')
    # ### end Alembic commands ###
